version: '3.8'

services:
  # symfony/mailer
  mailer:
    image: schickling/mailcatcher
    ports: [1025, 1080]

  redis:
    image: redis:5-alpine
    ports: [6379]
    
  rabbitmq:
    image: rabbitmq:3.7-management
    ports: [5672, 15672]
  
  php-fpm:
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672